### PR TITLE
Update to latest React Native setup

### PR DESCRIPTION
**Pull request by frederickfogerty**

### CODE REVIEW

**Comment by arunoda** [comment]
Guys, take this in. 
CC @mnmtanish @roonyh

**Comment by frederickfogerty** [comment]
Hey @arunoda, thanks for looking at my PR.

I've been playing around with getting React Native Storybook to run on my device, and if you define the location in AppDelegate.m as 

``` objective-c
#ifdef STORYBOOK
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"storybook/index.ios" fallbackResource:nil];
#else
  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
#endif
```

it makes the location dynamic based on whether it's running in a simulator, or on a device. I'll update my PR now.

**Comment by frederickfogerty** [comment]
I've also added another step to tell people to add a `storybook/index.ios.js` file, as it wasn't clear to me to do this when I was setting up React Native Storybook

**Comment by arunoda** [comment]
@frederickfogerty Yeah! That step is needed. People might get confused.

**Pull request merged**
